### ISSUE TITLE
errors when changing with_label = True 

### ISSUE THREAD

**Issue by bootcap** [issacchan26/HumanPartSegmentation#1]
I got the following errors when I ran this reop:

'''
Traceback (most recent call last):
  File "test.py", line 159, in <module>
    predict(with_label=with_label)
  File "test.py", line 142, in predict
    eval_acc, pred_list = test(test_loader)
ValueError: not enough values to unpack (expected 2, got 1
'''

It seems your data.y is always None in the function test().

**Comment by issacchan26** [comment]
> I got the following errors when I ran this reop:
> 
> ''' Traceback (most recent call last): File "test.py", line 159, in predict(with_label=with_label) File "test.py", line 142, in predict eval_acc, pred_list = test(test_loader) ValueError: not enough values to unpack (expected 2, got 1 '''
> 
> It seems your data.y is always None in the function test().

Thank you for reporting the issue, the script has been updated but I did not push to Github. I will test the script again and update the repo.

**Comment by issacchan26** [comment]
> I got the following errors when I ran this reop:
> 
> ''' Traceback (most recent call last): File "test.py", line 159, in predict(with_label=with_label) File "test.py", line 142, in predict eval_acc, pred_list = test(test_loader) ValueError: not enough values to unpack (expected 2, got 1 '''
> 
> It seems your data.y is always None in the function test().

Thank you for reporting the issue
After checking with the codes, the code works fine with appropriate setting.
When you change the with_label from False to True, you need to delete the "processed" folder in your parent data folder. As PYG will not replace the processed folder, the processed data will remain without labels so that the error will occur.

Please also remind that the ground truth are stored in .txt files while .ply cannot store any annotations. So the input data format is different between testing (with_label = False) and evaluation (with_label = True), you may reference to the eval_data folder and test_data folder for details.
